FROM python:3.11-slim

RUN pip install poetry

RUN poetry config virtualenvs.create false

WORKDIR /code

COPY ./pyproject.toml ./README.md  ./

COPY ./package[s] ./packages

RUN poetry install  --no-interaction --no-ansi --no-root

COPY ./app ./app

RUN poetry install --no-interaction --no-ansi

EXPOSE 8080

CMD poetry run serve
